/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.mongo;

import org.junit.Test;

import org.mule.module.mongo.MongoCloudConnector;

public class MongoTestCase
{
    @Test
    public void invokeSomeMethodOnTheCloudConnector()
    {
    /*
        Add code that tests the cloud connector at the API level. This means that you'll
        instantiate your cloud connector directly, invoke one of its methods and assert
        you get the correct result.

        Example:

        mongoCloudConnector connector = new mongoCloudConnector();
        Object result = connector.someMethod("sample input");
        assertEquals("expected output", result);
     */
    }
}
