/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.mongo.config;

import org.mule.construct.SimpleFlowConstruct;
import org.mule.tck.FunctionalTestCase;

public class MongoNamespaceHandlerTestCase extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return"mongo-namespace-config.xml";
    }

    public void testSendMessageToFlow()throws Exception
    {
        lookupFlowConstruct("CreateCollection");
    }

    private SimpleFlowConstruct lookupFlowConstruct(String name)
    {
        return(SimpleFlowConstruct)muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
